"""add_skills_module

Revision ID: 1d4c7aaabb0b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 14:15:18.034550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d4c7aaabb0b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_definitions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='general', nullable=False),
    sa.Column('sub_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('current_level', sa.String(length=20), server_default='beginner', nullable=False),
    sa.Column('total_practice_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_definitions_user_active', 'skill_definitions', ['user_id', 'is_active'], unique=False)
    op.create_table('competency_levels',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('sub_skill', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('stability', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('last_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competency_levels_next_review', 'competency_levels', ['next_review_date'], unique=False)
    op.create_index('idx_competency_levels_skill', 'competency_levels', ['skill_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('quality_rating', sa.SmallInteger(), nullable=False),
    sa.Column('focus_area', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('practiced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_practice_sessions_skill', 'practice_sessions', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_practice_sessions_skill', table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index('idx_competency_levels_skill', table_name='competency_levels')
    op.drop_index('idx_competency_levels_next_review', table_name='competency_levels')
    op.drop_table('competency_levels')
    op.drop_index('idx_skill_definitions_user_active', table_name='skill_definitions')
    op.drop_table('skill_definitions')
    # ### end Alembic commands ###
