"""add_partial_completion_counts_and_programs

Revision ID: 1f7e7ed0bb5c
Revises: 1ce9fc86d6fc
Create Date: 2026-02-09 13:41:56.699330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7e7ed0bb5c'
down_revision: Union[str, Sequence[str], None] = '1ce9fc86d6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_programs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('workouts_per_week', sa.Integer(), server_default='3', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_programs_user', 'workout_programs', ['user_id'], unique=False)
    op.create_table('program_weeks',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('prescriptions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('progression_source', sa.String(length=20), nullable=True),
    sa.Column('recovery_rating', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['workout_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'week_number', name='uq_program_week')
    )
    op.create_index('idx_program_weeks_program', 'program_weeks', ['program_id'], unique=False)
    op.add_column('habit_definitions', sa.Column('partial_completion_counts', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('workout_sessions', sa.Column('program_id', sa.UUID(), nullable=True))
    op.add_column('workout_sessions', sa.Column('program_week_id', sa.UUID(), nullable=True))
    op.add_column('workout_sessions', sa.Column('program_day_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout_sessions', 'workout_programs', ['program_id'], ['id'])
    op.create_foreign_key(None, 'workout_sessions', 'program_weeks', ['program_week_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_column('workout_sessions', 'program_day_index')
    op.drop_column('workout_sessions', 'program_week_id')
    op.drop_column('workout_sessions', 'program_id')
    op.drop_column('habit_definitions', 'partial_completion_counts')
    op.drop_index('idx_program_weeks_program', table_name='program_weeks')
    op.drop_table('program_weeks')
    op.drop_index('idx_workout_programs_user', table_name='workout_programs')
    op.drop_table('workout_programs')
    # ### end Alembic commands ###
