"""add fitness module

Revision ID: 9fb2443e3e2b
Revises: 3619fa0c70a6
Create Date: 2026-02-06 19:42:55.325067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fb2443e3e2b'
down_revision: Union[str, Sequence[str], None] = '3619fa0c70a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('muscle_groups', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exercises_category', 'exercises', ['category'], unique=False)
    op.create_index('idx_exercises_user', 'exercises', ['user_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_templates_user', 'workout_templates', ['user_id'], unique=False)
    op.create_table('template_exercises',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('target_sets', sa.Integer(), server_default='3', nullable=False),
    sa.Column('target_reps', sa.Integer(), server_default='10', nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('set_type', sa.String(length=20), server_default='working', nullable=False),
    sa.Column('rest_seconds', sa.Integer(), server_default='120', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_exercises_template', 'template_exercises', ['template_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_sessions_status', 'workout_sessions', ['user_id', 'status'], unique=False)
    op.create_index('idx_workout_sessions_user', 'workout_sessions', ['user_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), server_default='0', nullable=False),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rpe', sa.SmallInteger(), nullable=True),
    sa.Column('set_type', sa.String(length=20), server_default='working', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_sets_exercise', 'workout_sets', ['exercise_id'], unique=False)
    op.create_index('idx_workout_sets_session', 'workout_sets', ['session_id'], unique=False)
    op.alter_column('activity_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('habit_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('habit_completions', 'value',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('habit_completions', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('habit_definitions', 'frequency_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('habit_definitions', 'target_value',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('habit_definitions', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''#4CAF50'''::character varying"))
    op.alter_column('habit_definitions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('habit_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('habit_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('habit_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('habit_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('habit_definitions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('habit_definitions', 'color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''#4CAF50'''::character varying"))
    op.alter_column('habit_definitions', 'target_value',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('habit_definitions', 'frequency_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('habit_completions', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('habit_completions', 'value',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('habit_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_workout_sets_session', table_name='workout_sets')
    op.drop_index('idx_workout_sets_exercise', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index('idx_workout_sessions_user', table_name='workout_sessions')
    op.drop_index('idx_workout_sessions_status', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index('idx_template_exercises_template', table_name='template_exercises')
    op.drop_table('template_exercises')
    op.drop_index('idx_workout_templates_user', table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index('idx_exercises_user', table_name='exercises')
    op.drop_index('idx_exercises_category', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
